apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 9.4.1
    helm:
      valueFiles:
      - $values/argocd/values.yaml
  - repoURL: 'https://github.com/Queer-In-Tech/k8s-apps.git'
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
