apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  sources:
  - repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: "0.27.0"
    chart: cloudnative-pg 
    helm:
      valueFiles:
      - $values/cloudnative-pg/values.yaml
  - repoURL: 'https://github.com/Queer-In-Tech/k8s-apps.git'
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloudnative-pg
