apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  sources:
  - repoURL: 'https://github.com/Queer-In-Tech/k8s-apps.git'
    path: forgejo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: forgejo
