apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 1
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
  storage:
    size: 5Gi
    storageClass: longhorn-single-replica