apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-postgres
spec:
  instances: 1
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
  storage:
    size: 5Gi
    storageClass: longhorn-single-replica