apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-postgres
spec:
  instances: 1
  bootstrap:
    initdb:
      database: vaultwarden
      owner: vaultwarden
  storage:
    size: 5Gi
    storageClass: longhorn-single-replica
