apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vaultwarden
spec:
  selector:
    matchLabels:
      app: vaultwarden 
  serviceName: "vaultwarden"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: vaultwarden
        image: {{ .Values.vaultwarden.image }}:{{ .Values.vaultwarden.tag }}
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: vaultwarden
          mountPath: /data
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: vaultwarden
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
